name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # We don't need working-directory for --version
      - name: Verify Environment
        run: |
          sf --version
          node --version

      - name: Validate Project Structure
        working-directory: ./traveltrust
        run: |
          test -f sfdx-project.json
          test -d force-app
          echo "Success: Project files found in traveltrust directory."