name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      - name: Show CLI version
        run: sf --version

      - name: Debug repo root
        run: |
          echo "PWD:"
          pwd
          echo "Root files:"
          ls -la
          echo "force-app contents (if exists):"
          ls -la force-app || true
          

      - name: Validate project structure
        run: |
          test -f sfdx-project.json
          test -d force-app
